sudo: required
dist: trusty
language: c++
compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y qtbase5-dev 
    - sudo apt-get install -y libsdl1.2-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make

