language: c++

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qtbase5-dev 
    - sudo apt-get install -qq libsdl1.2-dev
    - sudo apt-get install -qq cmake

script:
    - cmake .
    - make

